### ISSUE TITLE
go mod tidy seems to automatically get v1.2.0

### ISSUE THREAD

**Issue by ds-281** [omeid/uconfig#16]
Hello,

It seems that using uconfig causes `go mod tidy` to fetch v1.2.0 by default. At the very least, on `go1.21.5 linux/amd64`.

```
user@hostname > /tmp/foo > vim main.go # here just copy/paste the first full example from the README and remove redis/database references 
user@hostname > /tmp/foo > go mod init foo
go: creating new go.mod: module foo
go: to add module requirements and sums:
	go mod tidy
user@hostname > /tmp/foo > go mod tidy
go: finding module for package github.com/omeid/uconfig
go: found github.com/omeid/uconfig in github.com/omeid/uconfig v1.2.0
user@hostname > /tmp/foo > go version
go version go1.21.5 linux/amd64
```

This causes the version of `uconfig` to be somewhat outdated. I noticed this because the USAGE column was nowhere to be found upon calling `.Usage()` and decided to investigate a bit. Editing the `go.mod` to point towards 0.5 instead naturally works.

**Comment by omeid** [comment]
I think it is potentally related to golang/go#39007.

I have now pushed a new tag for v1.2.0 with the retraction that was pushed earlier on, and see if that covers it.

**Comment by ds-281** [comment]
It might be. The tag pushed however did not fix it, sadly.

```
user@hostname > /tmp/foo > go build
# foo
./main.go:23:35: too many values in struct literal of type struct{Path string; Unmarshal file.Unmarshal}
```

(this happens in older versions of uconfig, where the optional flag for Files wasn't present)

**Comment by omeid** [comment]
I had to push a higher version that retracts 1.2.0 as well as itself (1.2.1). It should be fixed now.

**Comment by ds-281** [comment]
Yup, that did it. Thanks!
